 server:
   port:
---
     spring:
       config:
         activate:
           on-profile: local
     server:
       port: 8080
---
     spring:
       config:
         activate:
           on-profile: dev
     server:
       port: 8081

 property:
          test:
            name: property depth test
            propertyTest:test
            propertyTestList:a,b,c